site_name: Jupiter Broadcasting - Show Notes
site_url: https://notes.selfhosted.show
repo_url: https://github.com/selfhostedshow/show-notes
repo_name: selfhostedshow/show-notes
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/regular/folder-open
  palette:
    primary: light blue
    accent: white
    scheme: slate
  font:
    code: Jet Brains Mono
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
  custom_dir: theme

plugins:
  - search

markdown_extensions:
  - abbr
  - admonition # enables coloured blocks mid article
  - attr_list # improves image handling
  - pymdownx.details # enables collapsible admonitions
  - footnotes
  - meta # adds support for front matter
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.highlight: # code highlighting
      linenums: true
  - pymdownx.tabbed # enables tabs for embedded blocks
  - pymdownx.snippets
  - pymdownx.superfences # allows for the nesting of code blocks inside other blocks
  - pymdownx.keys

copyright: 2020 - 2021 &copy; Alex Kretzschmar - Licensed under GPLv3

extra:
  shows:
    self-hosted:
      fireside_url: https://selfhosted.show
      theme:
        primary: orange
        accent: amber
    coder-radio:
      fireside_url: https://coder.show
      theme:
        primary: blue
        accent: red
    linux-action-news:
      fireside_url: https://linuxactionnews.com
      theme:
        primary: red
        accent: white
    linux-unplugged:
      fireside_url: https://linuxunplugged.com
      theme:
        primary: blue
        accent: cyan
