name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # scrape fireside for latest shows
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install -U -r requirements.txt
          python3 scrape.py

      # automatically adds changed files in docs directory to git
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatically scraped and committed via a GitHub Action."

           
      # # Build
      # - name: Pull latest changes on VPS
      #   uses: appleboy/ssh-action@master
      #   with:
      #       host: ${{ secrets.VPS_HOST }}
      #       USERNAME: ${{ secrets.VPS_DEPLOY_USER }}
      #       PORT: ${{ secrets.VPS_SSH_PORT }}
      #       KEY: ${{ secrets.VPS_SSHKEY }}
      #       script: cd ${{ secrets.VPS_PROJECT_PATH }} && git fetch && git checkout main && git pull
      # - name: Build
      #   uses: appleboy/ssh-action@master
      #   with:
      #       host: ${{ secrets.VPS_HOST }}
      #       USERNAME: ${{ secrets.VPS_DEPLOY_USER }}
      #       PORT: ${{ secrets.VPS_SSH_PORT }}
      #       KEY: ${{ secrets.VPS_SSHKEY }}
      #       script: cd ${{ secrets.VPS_PROJECT_PATH }} && docker-compose run pms-wiki build

      # # Deploy
      # - name: Deploy new image and cleanup
      #   uses: appleboy/ssh-action@master
      #   with:
      #       host: ${{ secrets.VPS_HOST }}
      #       USERNAME: ${{ secrets.VPS_DEPLOY_USER }}
      #       PORT: ${{ secrets.VPS_SSH_PORT }}
      #       KEY: ${{ secrets.VPS_SSHKEY }}
      #       script: docker-compose -f ~/docker-compose.yml up -d && docker image prune -af